[package]
name = "object-detection-rs"
version = "0.1.0"
authors = ["Mason Stallmo <masonstallmo@gmail.com>"]
edition = "2018"

[dependencies]
tensorflow = "0.11.0"
image = "0.20.1"
ndarray = "0.12.1"
imageproc = "0.17.0"